name: "lint & build changed ports"

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }}
    timeout-minutes: 0
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14]

    steps:
      - name: Checkout ports
        uses: actions/checkout@v4
        with:
          fetch-depth: 64
          path: ports
          show-progress: false
      - name: Checkout mpbb
        uses: actions/checkout@v4
        with:
          repository: macports/mpbb
          path: mpbb
          show-progress: false
      - name: Bootstrap MacPorts
        run: . ports/.github/workflows/bootstrap.sh
      - name: Determine list of changed ports
        id: portlist
        run: |
          set -eu
          # Add getopt, mpbb and the MacPorts paths to $PATH for the subsequent
          # steps.
          echo "/opt/mports/bin" >> $GITHUB_PATH
          echo "${PWD}/mpbb" >> $GITHUB_PATH
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

          portlist=$(/opt/local/bin/port echo 'depends::ImageMagick(\s|$)' | xargs echo)

          echo "$portlist"
          echo "portlist=$portlist" >> $GITHUB_OUTPUT

      - name: Determine list of subports from portlist
        id: subportlist
        run: |
          set -eu

          echo "#### Changed Ports" >> $GITHUB_STEP_SUMMARY

          subportlist=""
          echo "::group::Listing subports"
          new_subports="$portlist"
          for subport in $new_subports; do
            echo "$subport"
            echo "- ${subport}" >> $GITHUB_STEP_SUMMARY
            subportlist="$subportlist $subport"
          done
          echo "::endgroup::"

          echo "subportlist=${subportlist}" >> $GITHUB_OUTPUT
        env:
          portlist: ${{ steps.portlist.outputs.portlist }}
      - name: Check linkage of subports
        run: |
          set -eu

          echo "#### Build Results" >> $GITHUB_STEP_SUMMARY

          /opt/local/bin/port-tclsh ports/.github/workflows/linkswith.tcl --portlist "$subportlist"
           
        env:
          subportlist: ${{ steps.subportlist.outputs.subportlist }}
      - name: Make logfiles readable
        if: always()
        run: |
          mkdir -p /tmp/mpbb
          sudo find \
            /tmp/mpbb \
            -maxdepth 1 \
            -mindepth 1 \
            -type d \
            -print \
            -exec chmod -R go+rX {} \;
      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}.zip
          path: /tmp/mpbb/*/logs
